#!/usr/bin/env node
// Walks `<bin> [sub...] --help` recursively and writes one Starlight Markdown page per command.
// Usage: node refgen/help2md.mjs --bin <path-or-name> [--out <dir>]
import { execFileSync } from 'node:child_process';
import { mkdirSync, readdirSync, rmSync, writeFileSync } from 'node:fs';
import { basename, join } from 'node:path';
import { parseArgs } from 'node:util';

// Fixed width and no colors so output is identical on every machine and CI run.
const ENV = { ...process.env, COLUMNS: '100', NO_COLOR: '1', CLICOLOR: '0', TERM: 'dumb' };
const MAX_DEPTH = 8;

const help = (bin, path) =>
  execFileSync(bin, [...path, '--help'], { env: ENV, encoding: 'utf8', stdio: ['ignore', 'pipe', 'pipe'] })
    .split('\n').map((l) => l.trimEnd()).join('\n').trim();

// Subcommand names from clap ("Commands:", clap 3 "SUBCOMMANDS:") and cobra ("Available Commands:",
// "Additional Commands:", command-group titles) sections. Entries sit at a 2-space indent; deeper
// lines are wrapped descriptions.
function subcommands(text) {
  const names = [];
  let inSection = false;
  for (const line of text.split('\n')) {
    if (/^(\w[\w ]*)?commands:$/i.test(line)) inSection = true;
    else if (!line.trim() || /^\S/.test(line)) inSection = false;
    else if (inSection) {
      const m = /^ {2}([\w][\w.-]*)(?:\s+(.*))?$/.exec(line);
      if (m && !skip(m[1], m[2] ?? '')) names.push(m[1]);
    }
  }
  return names;
}

// `help` only repeats other pages. Cobra's default `completion` is identical boilerplate in every
// cobra CLI, so it is recognised by its stock description; a project's own `completion` stays.
const skip = (name, desc) =>
  name === 'help' || (name === 'completion' && desc.startsWith('Generate the autocompletion script'));

function page(title, text) {
  const description = text.split('\n')[0];
  const fence = '`'.repeat(Math.max(3, ...(text.match(/`+/g) ?? []).map((s) => s.length + 1)));
  return [
    '---',
    `title: ${JSON.stringify(title)}`,
    ...(description && !/^usage:/i.test(description) ? [`description: ${JSON.stringify(description)}`] : []),
    '---',
    '',
    '<!-- Generated by docs-kit refgen/help2md from --help output. Do not edit. -->',
    '',
    `${fence}text`,
    text,
    fence,
    '',
  ].join('\n');
}

function generate(bin, out) {
  const root = basename(bin).toLowerCase();
  mkdirSync(out, { recursive: true });
  // Drop pages of commands that no longer exist so the "reference up to date" check sees removals.
  // ponytail: prefix match also hits a sibling binary's pages (`kasha` vs `kasha-server`) in the same
  // --out; give each binary its own --out if that ever happens.
  for (const f of readdirSync(out)) {
    if (f === `${root}.md` || (f.startsWith(`${root}-`) && f.endsWith('.md'))) rmSync(join(out, f));
  }
  const walk = (path) => {
    if (path.length > MAX_DEPTH) throw new Error(`command tree deeper than ${MAX_DEPTH}: ${path.join(' ')}`);
    const text = help(bin, path);
    const file = [root, ...path].join('-').toLowerCase() + '.md';
    writeFileSync(join(out, file), page([root, ...path].join(' '), text));
    for (const sub of subcommands(text)) walk([...path, sub]);
  };
  walk([]);
}

const { values } = parseArgs({
  options: { bin: { type: 'string' }, out: { type: 'string', default: 'docs/src/content/docs/reference/cli' } },
});
if (!values.bin) {
  console.error('usage: help2md.mjs --bin <path-or-name> [--out <dir>]');
  process.exit(2);
}
generate(values.bin, values.out);
